{"uuid": "5bb17a6e-fe7e-4396-803f-0cfc0c199cbd", "children": ["4e339aa5-042c-4d2d-8c51-a235669a4ca7"], "stop": 1610543678590, "befores": [{"start": 1610543668481, "name": "_Class__pytest_setup_class", "status": "broken", "stop": 1610543678494, "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .//input[@id='username']\n\n", "trace": "  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 921, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\python.py\", line 799, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\python.py\", line 732, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\auto_test\\Autotest_Demo\\Test\\Test_ ManagementCenter\\test_item_management.py\", line 19, in setup_class\n    self.loginpage.login_in('admin', '20202020', '', '管理员1')\n  File \"D:\\auto_test\\Autotest_Demo\\page\\login_page.py\", line 19, in login_in\n    self.send_text(page.login_username,userName)\n  File \"D:\\auto_test\\Autotest_Demo\\base\\base_page.py\", line 40, in send_text\n    self.find_ele(loc).clear()\n  File \"D:\\auto_test\\Autotest_Demo\\base\\base_page.py\", line 21, in find_ele\n    return self.driver.find_element(loc[0], loc[1])\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}}], "start": 1610543668481}