{"uuid": "b253cece-e6c4-431d-84ca-41ce0874f6a3", "stop": 1610894639425, "children": ["cce8d6bf-448e-4728-a59e-ea5801e167cf"], "start": 1610894608566, "befores": [{"status": "broken", "name": "_Class__pytest_setup_class", "stop": 1610894639127, "start": 1610894608566, "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=netTimeout&u=http%3A//10.194.188.76/homePage&c=UTF-8&d=10.194.188.76%20%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%93%8D%E5%BA%94%E6%97%B6%E9%97%B4%E8%BF%87%E9%95%BF%E3%80%82\n\n", "trace": "  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 921, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\python.py\", line 799, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\python.py\", line 732, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\auto_test\\Autotest_Demo\\test\\test_ management_center\\test_department_manage.py\", line 30, in setup_class\n    self.driver = DriverUtils.get_driver(self.url)\n  File \"D:\\auto_test\\Autotest_Demo\\utils.py\", line 16, in get_driver\n    cls._driver.get(url)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}}]}