{"uuid": "471665f2-5260-47d8-b297-4e1b7a2defb3", "children": ["b4ba653b-3d2c-49c6-9a99-800e75f04d12", "9b69fba1-7625-4a84-90e4-ea2384abf28f", "c7de100f-798b-4f99-bc83-174bae8b53f4", "a8d13b95-0e38-4d2f-9036-99e655d0e9d4"], "stop": 1610543688823, "befores": [{"start": 1610543678607, "name": "_Class__pytest_setup_class", "status": "broken", "stop": 1610543688617, "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .//input[@id='username']\n\n", "trace": "  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 921, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\python.py\", line 799, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\python.py\", line 732, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\auto_test\\Autotest_Demo\\Test\\Test_ ManagementCenter\\test_role_preserve.py\", line 19, in setup_class\n    self.loginpage.login_in('admin', '20202020', '', '管理员1')\n  File \"D:\\auto_test\\Autotest_Demo\\page\\login_page.py\", line 19, in login_in\n    self.send_text(page.login_username,userName)\n  File \"D:\\auto_test\\Autotest_Demo\\base\\base_page.py\", line 40, in send_text\n    self.find_ele(loc).clear()\n  File \"D:\\auto_test\\Autotest_Demo\\base\\base_page.py\", line 21, in find_ele\n    return self.driver.find_element(loc[0], loc[1])\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}}], "start": 1610543678607}