{"children": ["8f815c57-e057-45e7-ae06-d4c37e60a661", "a3a47953-2d40-4c9c-bd2e-1d888a64c2a6", "8dca772d-dc36-40df-8f0c-1d7b3ca4448d", "e52368e3-a8ac-4f5e-b33e-2aea9ad99f65"], "stop": 1610978828339, "befores": [{"start": 1610978800456, "stop": 1610978828036, "name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=netTimeout&u=http%3A//10.194.188.76/homePage&c=UTF-8&d=10.194.188.76%20%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%93%8D%E5%BA%94%E6%97%B6%E9%97%B4%E8%BF%87%E9%95%BF%E3%80%82\n\n", "trace": "  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 921, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\python.py\", line 799, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\python.py\", line 732, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\auto_test\\Autotest_Demo\\test\\test_ management_center\\test_department_manage.py\", line 44, in setup_class\n    self.driver = DriverUtils.get_driver(self.url)\n  File \"D:\\auto_test\\Autotest_Demo\\utils.py\", line 16, in get_driver\n    cls._driver.get(url)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}}], "start": 1610978800456, "uuid": "d03774a1-e6c3-4c12-b54c-8bef7ce661fa"}